name: Automação de Atualização de Conteúdo

on:
  schedule:
    - cron: "0 0 * * 0" # Executar semanalmente (domingo à meia-noite)
  workflow_dispatch: # Permitir execução manual via interface do GitHub

jobs:
  update-content:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Instalar dependências
        run: pip install requests beautifulsoup4

      - name: Executar o script de atualização
        run: python update_content.py

      - name: Commit e Push das alterações
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add site/
          git commit -m "Atualização automática dos tópicos"
          git push origin main
