name: Automação de Atualização de Conteúdo

on:
  schedule:
    - cron: "0 0 * * 0" # Executar semanalmente (domingo à meia-noite)
  workflow_dispatch: # Permitir execução manual via interface do GitHub

jobs:
  update-content:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Instalar dependências
        run: pip install requests beautifulsoup4 googletrans==4.0.0-rc1

      - name: Executar o script de atualização
        run: python update_content.py

      - name: Verificar se há alterações
        id: changes
        run: |
          if git diff --quiet; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit e Push das alterações
        if: steps.changes.outputs.changes == 'true'
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add teoria-musical-wikipedia.html
          git commit -m "Atualização automática dos conteúdos da Wikipedia"
          git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
